### ISSUE TITLE
switchMode() Q1. Unnecessary line `::RemoveMenu(_hMenu, _posBase+1, MF_BYPOSITION);`  ? 

### ISSUE THREAD

**Issue by victorel-petrovich** [victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp#3]
https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/blob/master/PowerEditor/src/lastRecentFileList.cpp

The line in question is indicated below: 
```c++
void LastRecentFileList::switchMode()
{
	//Remove all menu items
	//....

	if (_hParentMenu == NULL) // mode main menu
	{	
                //...

		// switch to sub-menu mode
		_hParentMenu = _hMenu;
		_hMenu = ::CreatePopupMenu();
		::RemoveMenu(_hMenu, _posBase+1, MF_BYPOSITION);  // ???????????????????????????????????
	}
	else // mode sub-menu
	{
		// ...
	}
	_hasSeparators = false;
}

```
What is that line doing, if menu `_hMenu` created by `CreatePopupMenu()` is already empty?

**Comment by victorel-petrovich** [comment]
I wish we had the ability to comment right beside a file in question.

**Comment by Yaron10** [comment]
@victorel-petrovich,

https://github.com/molsonkiko/notepad-plus-plus/commit/bc0f6b3de89ca8a36ca38a362421ce03e282e809#commitcomment-120644607.

**Comment by victorel-petrovich** [comment]
@Yaron10  , thank you for the hint !  and the  link with steps. 
I signed up there and have run the build process. But, as you can see in pictures below -- please click to see a larger picture --
- it's showing 8.4.1 ; does that mean the 8.4.1 version of N++? 

![currentbuild](https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/assets/11040279/db03f0d0-420f-4216-8686-6e6b357b93b6)

- I don't know how to get a working portable version (my preference) or installer. 
- when I click on first one, then on Artifacts, I see this: 
![first one](https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/assets/11040279/14dfdaa7-ffdf-47df-936f-d77f89bae8d1)

- I downloaded that .exe (as I run windows 32 bit) but when I run it, it complains in several popup windows `Load langs.xml failed!` and `Load stylers.xml failed` 

So I think it's executable that's supposed to go inside Portable version, except that it is bare naked (outside its folder). 

Do you know how to get the proper full Portable ? or maybe a page somewhere that explains the process ?

**Comment by victorel-petrovich** [comment]
However: what I just tried is to put that .exe above inside my current Portable version (latest 8.5.4).
Then when I run, and look debug info, then I don't see any difference from the default/original .exe in that Portable folder. 

Is that how I was supposed to do it?

**Comment by alankilborn** [comment]
>So I think it's executable that's supposed to go inside Portable version, except that it is bare naked (outside its folder).

>Do you know how to get it properly ? or maybe a page somewhere that explains the process ?

It's hard for me to exactly tell but I think you want this?:
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing

**Comment by Yaron10** [comment]
@victorel-petrovich,

You're welcome.

> it's showing 8.4.1

This is AppVeyor's internal number.

> So I think it's executable that's supposed to go inside Portable version, except that it is bare naked (outside its folder).

Correct.

> However: what I just tried is to put that .exe above inside my current Portable version (latest 8.5.4).
Then when I run, and look debug info, then I don't see any difference from the default/original .exe in that Portable folder. Including the N++ version (shows 8.5.4 too)
>
> Is that how I was supposed to do it?

That's how it's supposed to be.
If you run your file, you should get a different behavior according to the changes you've made.

**TIP:**
You can cancel the build once the x32 is ready - so that if you make new(er) changes, a new build would start immediately. 

> Do you know how to get it properly ? or maybe a page somewhere that explains the process ?

@alankilborn has provided the link.

You can download the source code and build it with MS Visual Studio, or "Open with GitHub Desktop". I've never tried the latter.

![תמונה](https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/assets/10229320/105afc3b-3859-447b-b3d3-85201253f24e)

**Comment by Yaron10** [comment]
@victorel-petrovich,

Please let me know when your build is ready for testing.

Thank you.

**Comment by victorel-petrovich** [comment]
@alankilborn
Thanks for the reference, it has some good tips. It confirmed my guess of what to do with the downloaded .exe. 

But it advises to download the "debug" version, not "release", though it doesn't explain why. 
I guess it's for displaying more errors/warnings if there are any, but for that, I guess one would need to run it from the cmd window (cmd line) and the warnings/errors would appear there. 

@Yaron10 
Thanks for the detailed reply and removing my doubts. 
> You can cancel the build once the x32 is ready - so that if you make new(er) changes, a new build would start immediately.

I will use that. 

And the code line described in this issue: 
I just tested commenting it out; appears indeed redundant. No difference whatsoever in behavior of the executable (either "Release" or "Debug"). I've actually run them with `-multiInstance`, besides the original version N++. 

So I'm "unstuck" now and will continue with understanding the rest of the 
lastRecentFileList.cpp file .

**Comment by Yaron10** [comment]
@victorel-petrovich,

My pleasure.

> //::RemoveMenu(_hMenu, _posBase+1, MF_BYPOSITION); // ?? what's this line doing? isnt the new menu created by CreatePopupMenu() empty?

This is **apparently** a good question.

> So I'm "unstuck" now and will continue with understanding the rest of the
lastRecentFileList.cpp file .

Thank you for that and best of luck.

**Comment by victorel-petrovich** [comment]
@Yaron10 
> Please let me know when your build is ready for testing.

I have further questions (see for example the new open issue; then a couple of others in the pipeline), 
do you know whom I could discuss them with? Someone who has some experience with menus in N++?

**Comment by Yaron10** [comment]
@victorel-petrovich,

Sorry for the late reply. I wasn't by my PC.

@ ozone10 (remove the space). But he hasn't been active recently.

**Comment by victorel-petrovich** [comment]
@Yaron10 , not too late at all, thanks

**Comment by Yaron10** [comment]
@victorel-petrovich,

> This is **apparently** a good question.

Just wanted to add that I had tested your build with that line commented and couldn't find a problem.

**Comment by victorel-petrovich** [comment]
@Yaron10  , thanks, I should consider this settled then.

**Comment by Yaron10** [comment]
Apparently. :)
There's always a chance we've both missed some corner-case.

**Comment by victorel-petrovich** [comment]
I checked using print statements before and after that line, looking at size and id-s in submenu ; confirms that line does nothing at all.
