### ISSUE TITLE
updateMenu() Q2. Unclear (unnecessary ) line, separator should already be absent ? 

### ISSUE THREAD

**Issue by victorel-petrovich** [victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp#5]
Click link below:
https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/blob/7cabf5d1769b9bb9916a7027a08238667f9a02c0/PowerEditor/src/lastRecentFileList.cpp#L362

The comment says "// Remove the last left separator from the submenu " ,
 but , looking at the logic there, there is no left separator/bar (------------------) in the submenu at that point in flow. There is only 1 bar ever in that submenu, and it has been removed lines above it

**Comment by victorel-petrovich** [comment]
Actually, testing shows that commenting that line leads to a extra bar(separator) appearing at the top of that submenu whenever Empty the recent file list, and then make it have again 1 file (or more) in the recent's list. 

So, the line is necessary, but I don't understand why?

**Comment by Yaron10** [comment]
@victorel-petrovich,

1. Wrong/redundant code is _not uncommon_ in most applications.
2. I remember working on separators in the Window menu. It IS tricky.

I suggest that you concentrate on moving the commands below the files list.
There's a better chance of discussing your good questions when the PR is reviewed.

**Comment by victorel-petrovich** [comment]
@Yaron10 , Good to know someone else also found them tricky :) 
To make the PR I need to understand the code first ... But I'll try. 

By the way, I was thinking today, do you know an easy way to speed up the compilation on appveyor? Perhaps by removing some components of notepad++ that I don't need for my tests, like the entire Scintilla , Lexilla components maybe ? 
I already only build debug and for win 32 bit, but it still takes at least 6 minutes to get the artifact.

**Comment by Yaron10** [comment]
@victorel-petrovich,

> To make the changes for the PR I need to understand the code first

I am not a pro either, and it should take me some time to understand it too. :)

I suggest you have a look at:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f6e1b2cab6b42530869f600121443350f0292ad6/PowerEditor/src/Notepad_plus.cpp#L579
and analyze `_idBase` and `_posBase` in
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f6e1b2cab6b42530869f600121443350f0292ad6/PowerEditor/src/lastRecentFileList.cpp#L23

> Let me know if you know an easier way (but still with appveyor building).

Unfortunately I don't.

**Comment by victorel-petrovich** [comment]
@Yaron10 ,
I did look at those lines (from the very beginning). Have a look at the link inside this Issue now, Ive updated the link there a couple of hours ago, so that it shows a very commented version. 
In those comments, at initMenu() at top of file you'll see all about _posBase, _idBase... 

In fact, I commented so much, with diagrams, and in switchMenu() and updateMenu() that it should be easy for you or someone else to catch up and figure out what's going one there.

**Comment by victorel-petrovich** [comment]
Thanks for your time and ideas so far!
I'll think about your suggestion.

**Comment by victorel-petrovich** [comment]
Misleading code, for a beginner with menus...

Prev code indeed didn't remove that separator line because that code tried to remove at positions like `_posBase+k`, where there were no items at all... (all items inserted there automatically moved themselves to the top of the submenu, at first availalble spot at end of submenu)

**Comment by Yaron10** [comment]
@victorel-petrovich,

I've quickly tested "alt1", and it seems to work like a charm. Well done. 👍 

1. Could you please commit your final _code changes only_ so that I can compare them to the _original file_?
2. Could you build a _release_ artifact?
3. "alt 2" is wrong IMO. Both commands & files should be in the sub-menu.

Thank you.

**Comment by victorel-petrovich** [comment]
> I've quickly tested "alt1", and it seems to work like a charm. Well done. 👍

Thank you!

> Could you please commit your final code changes only so that I can compare them to the original file? 
Could you build a release artifact?

I guess you don't like my comments :) , k, I'll do that, and in actual release, For You :)

**Comment by victorel-petrovich** [comment]
> 3\. "alt 2" is wrong IMO. Both commands & files should be in the sub-menu.

It's not about wrong or not. It's speed when you try to access and navigate those recent files.

Moving the other 3 commands out of the submenu will make possible to navigate the files with arrows from both up and down direction, not having to skip over those 3 options, thus faster.

Makes sense?

And imagine this: you can change your access key for recent files, to open it with: `Alt+F+F` , and unique F sothat it directly opens the submenu. And there, with your left hand on Up/Down arrow keys,  you can select the filename very quickly.

**Comment by victorel-petrovich** [comment]
> I guess you don't like my comments :) , k, I'll do that, and in actual release, For You :)

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13925#issuecomment-1675665909

**Comment by Yaron10** [comment]
< I guess you don't like my comments

They might be helpful, but at this stage it would be much easier for me to understand the changes without them.
Could you please upload a file _without any new comments_?

> It's speed when you try to access and navigate those recent files.

I do understand that.
But this factor is not important to me nor to many other users.
OTOH, the correct structure of "Recent Files in Sub Menu" is both files and commands.

**Comment by Yaron10** [comment]
> It's speed when you try to access and navigate those recent files.

Also, you get the "speed" with "Alt 1". So why complicate things?

**Comment by victorel-petrovich** [comment]
> Could you please upload a file without any new comments?

Have you checked? I had done that. 

> OTOH, the correct structure of "Recent Files in Sub Menu" is both files and commands. 

hightly debatable :D . 

But doesn't matter, Don doesn't like either version. 

>  So why complicate things? 

Actually, alternative 2 is simpler. Both interface (Recent Files actually points to recent files), and code. Wait and you'll see; I"m going ahead and making it too, just for ... completion :)

**Comment by victorel-petrovich** [comment]
> Also, you get the "speed" with "Alt 1". 

I already explained in a prev comment why Alt 2 will be faster.

**Comment by Yaron10** [comment]
There are some comments and `printf`.

**Comment by victorel-petrovich** [comment]
where, link?

**Comment by victorel-petrovich** [comment]
Ok, removed the last printfs, you can skip the comments. Same link above.

**Comment by Yaron10** [comment]
https://github.com/pnedev/comparePlus/releases/tag/cp_1.1.0

If you compare your file to the original one, you'd realize that the extra comments and changing the functions position are distracting. :)

Anyway, you did a great job. 👍 

I'd suggest some minimal changes.

```cpp
void LastRecentFileList::updateMenu()
{
	NppParameters& nppParam = NppParameters::getInstance();
	bool isSubMenu = isSubMenuMode();
	int posBase= isSubMenu ? 0 : _posBase;

	if (!_hasSeparators && _size > 0)
	{
		// Add separators.
		NativeLangSpeaker *pNativeLangSpeaker = nppParam.getNativeLangSpeaker();

		generic_string recentFileList = pNativeLangSpeaker->getSubMenuEntryName("file-recentFiles");
		generic_string openRecentClosedFile = pNativeLangSpeaker->getNativeLangMenuString(IDM_FILE_RESTORELASTCLOSEDFILE);
		generic_string openAllFiles = pNativeLangSpeaker->getNativeLangMenuString(IDM_OPEN_ALL_RECENT_FILE);
		generic_string cleanFileList = pNativeLangSpeaker->getNativeLangMenuString(IDM_CLEAN_RECENT_FILE_LIST);

		if (recentFileList == TEXT(""))
			recentFileList = TEXT("&Recent Files");
		if (openRecentClosedFile == TEXT(""))
			openRecentClosedFile = TEXT("Restore Recent Closed File");
		if (openAllFiles == TEXT(""))
			openAllFiles = TEXT("Open All Recent Files");
		if (cleanFileList == TEXT(""))
			cleanFileList = TEXT("Empty Recent Files List");

		::InsertMenu(_hMenu, posBase, MF_BYPOSITION, static_cast<UINT_PTR>(-1), 0);		// Add a separator at the top in either mode.
		::InsertMenu(_hMenu, posBase + 1, MF_BYPOSITION, IDM_FILE_RESTORELASTCLOSEDFILE, openRecentClosedFile.c_str());
		::InsertMenu(_hMenu, posBase + 2, MF_BYPOSITION, IDM_OPEN_ALL_RECENT_FILE, openAllFiles.c_str());
		::InsertMenu(_hMenu, posBase + 3, MF_BYPOSITION, IDM_CLEAN_RECENT_FILE_LIST, cleanFileList.c_str());

		if (!isSubMenu)
		{
			::InsertMenu(_hMenu, posBase + 4, MF_BYPOSITION, static_cast<UINT_PTR>(-1), 0);		// A separator at the bottom.
		}
		else
		{
			::InsertMenu(_hParentMenu, _posBase, MF_BYPOSITION | MF_POPUP, reinterpret_cast<UINT_PTR>(_hMenu), (LPCTSTR)recentFileList.c_str());
			::InsertMenu(_hParentMenu, _posBase + 1, MF_BYPOSITION, static_cast<UINT_PTR>(-1), 0);
		}

		_hasSeparators = true;
	}
	else if (_hasSeparators && _size == 0)		// Remove separators.
	{
		::RemoveMenu(_hMenu, IDM_CLEAN_RECENT_FILE_LIST, MF_BYCOMMAND);
		::RemoveMenu(_hMenu, IDM_OPEN_ALL_RECENT_FILE, MF_BYCOMMAND);
		::RemoveMenu(_hMenu, IDM_FILE_RESTORELASTCLOSEDFILE, MF_BYCOMMAND);
		::RemoveMenu(_hMenu, posBase, MF_BYPOSITION);	// The separator at the top in both modes.

		if (!isSubMenu)
		{
			::RemoveMenu(_hMenu, posBase, MF_BYPOSITION);	// The separator at the bottom.
		}
		else
		{
			// Remove "Recent Files" Entry and the separator from the main menu.
			::RemoveMenu(_hParentMenu, _posBase + 1, MF_BYPOSITION);
			::RemoveMenu(_hParentMenu, _posBase, MF_BYPOSITION);
		}

		_hasSeparators = false;
	}

	_pAccelerator->updateFullMenu();

	// Remove all menu items.
	for (int i = 0; i < _size; ++i)
	{
		::RemoveMenu(_hMenu, _lrfl.at(i)._id, MF_BYCOMMAND);
	}
	// Then readd them, so everything stays in sync.
	for (int j = 0; j < _size; ++j)
	{
		generic_string strBuffer(BuildMenuFileName(nppParam.getRecentFileCustomLength(), j, _lrfl.at(j)._name) );
		::InsertMenu(_hMenu, posBase + j, MF_BYPOSITION, _lrfl.at(j)._id, strBuffer.c_str());
	}
}
```

***

If you're thinking of submitting a PR, I'd highly recommend to restore the original file's functions position.

**Comment by Yaron10** [comment]
Another option:

In `initMenu()` & `switchMode()` assign `posBase` or `0` to `_posBase`. 
Remove `int posBase = isSubMenu ? 0 : _posBase;` and use `_posBase` instead.

**Comment by Yaron10** [comment]
BTW, you can use `printInt()` & `printStr()` in release.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/de25873cb3352ee59d883e95e80c91806944e348/PowerEditor/src/MISC/Common/Common.cpp#L32

`printInt(_posBase);`.
 `printStr(TEXT("Some Text"));`.

**Comment by victorel-petrovich** [comment]
@Yaron10
The main thing for me was understanding what was going on with Don's hack with those displaced insertions in submenu. The rest was fairly easy.

> Another option:
> 
> In `initMenu()` & `switchMode()` assign `posBase` or `0` to `_posBase`. Remove `int posBase = isSubMenu ? 0 : _posBase;` and use `_posBase` instead.

That's a good idea. 

> `printInt(_posBase);`.
> `printStr(TEXT("Some Text"));`.

Will they show up a message box as the code says? And even in a release version, so I would not need say debugger or some other special setup?

**Comment by Yaron10** [comment]
> That's a good idea.

Thinking about it a bit more: it would require more code refactoring, and I'm not sure it's indeed a good idea.

> Will they show up a message box as the code says?

Yes.

> And even in a release version, so I would not need say debugger or some other special setup?

Correct.

**Comment by victorel-petrovich** [comment]
I've only been around this N++ project for a couple of weeks, but it seems to me Don is too conservative, too affraid of changes, too controlling. 
He should allow more maintainers to help him with reviewing and accepting changes.

**Comment by victorel-petrovich** [comment]
Tested those printInt(), printStr(), works. (if can't use a console and printf() ). 
 I used `TEXT("my string")` to avoid the error if use just `"string"`

**Comment by victorel-petrovich** [comment]
> If you're thinking of submitting a PR ... 

I don't (you've probably seen Don's replies ), but feel free to submit it yourself someday, if you want.

**Comment by Yaron10** [comment]
@victorel-petrovich,

People have different opinions and attitudes just like they have different faces. :)
I sometimes don't agree with Don, but I do respect him.

I suggest that you submit the PR (**only "Alt 1"**), and let Don review and test it.

**Comment by victorel-petrovich** [comment]
@Yaron10 
> but it seems to me Don is too conservative, too affraid of changes, too controlling. 

I guess that made it sound I don't respect him. Maybe I should have written "a bit too", not "too".
