### ISSUE TITLE
"Space to Tab (Leading)" does not convert spaces after tabs

### ISSUE THREAD

**Issue by Yaron10** [victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp#8]
@victorel-petrovich,

I was impressed by your persistence, intelligence and common-sense while working on "Recent Files".
Would you be interested in working on https://github.com/notepad-plus-plus/notepad-plus-plus/issues/ 12835 (remove the space)?

Thank you.

**Comment by victorel-petrovich** [comment]
> Notepad++ is Don's project, and I respect his prerogative to make the final decision even if I disagree. 

I guess you learned it's little use to openly disagree with him. Me, newbie, still learning through experimentation :)

> It's partially a personal interest: improving a software I use frequently. 

Makes sense. Have you thought of Textadept? I've read it's much more customizable, even menu structure etc, all in Lua. 

> And also - the more you "invest" in something, the more you care about it. 

Maybe also the community factor?..

> Certainly! I've been using my own modified build for a few years.
It's not forked on GitHub, but built with MS Visual Studio. 

Smart of you! I guess you're not alone. 
Maybe better for you to share your fork on Github? With MS VS it's probably easier to code/build, but on Github- easier to merge updates from the standard N++. And others may like your version, and maybe help with particular Issues you want... 

> I've integrated your "Recent Files" patch in my build! :) 

Good for you! I'll do the same. 

Thanks for sharing your thoughts.

**Comment by Yaron10** [comment]
> Have you thought of Textadept?

I may have tried it. But I'm used to NPP and ComparePlus.

> Maybe also the community factor?

There are many other communities. :)

> Maybe better for you to share your fork on Github?

I find it much easier to maintain my build on my PC.
Also - I've slightly adapted it to my personal use.

***

You're a gentleman.
I'd like to apologize for my request in https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/issues /5#issuecomment-1676000216 (remove the space).

Comparing the files was a bit confusing. 
But I realized later you were not aware of it.

**Comment by victorel-petrovich** [comment]
> There are many other communities. :)

Indeed :) 

> I'd like to apologize for my request ... 

Then you're a gentleman too :D 
No worry
Cheers !

**Comment by Yaron10** [comment]
Thank you!

Best regards.

**Comment by victorel-petrovich** [comment]
hello @Yaron10 ,
are you using load/save sessions? if yes: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14022

**Comment by Yaron10** [comment]
Hello @victorel-petrovich,

I've replied there.

**Comment by victorel-petrovich** [comment]
@Yaron10 , yes, I see the notifications

**Comment by Yaron10** [comment]
Hello @victorel-petrovich,

I don't want to bother others in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/ 14022.

> I'm not sure we'are on the same page:

I think we're both referring to Session files created by "File -> Save Session".

> So, talking about those special "session" xml files, I don't see for now why they can't be stored all in a single location.

They CAN be stored all in a single location.
And it seems that many users do that. - So my comparison to Visual Basic scripts was not quite accurate.
I would support your request/approach if it could be implemented by a few lines of code.
But unfortunately that's not the case.

I hope you understand.

I must retire now.
Good night.

**Comment by victorel-petrovich** [comment]
> I think we're both referring to Session files created by "File -> Save Session". 

Well then. I was simply confused by you mentioning there "Open/Save scripts" and wanted to make sure we talk about same thing. 

> I would support your request/approach if it could be implemented by a few lines of code.
But unfortunately that's not the case.
I hope you understand.

No problem at all! You already gave some support by simply commenting there. 
I mentioned you here just to get your attention, as I thought you'd be interested in that feature as well. 

It's not like I was rushing to implement that...

good night
